---
title: "HW5"
author: "Sahar Toulabi"
date: "2023-10-12"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE )
library(tidyverse)
library(dplyr)
library(tigris)
library(ggplot2)
library(sf)
library(forcats)
```

# **import data  and selected only Denver**

```{r}
homicides <- read_csv("/Users/sahartoulabi/Library/CloudStorage/OneDrive-Colostate/PostDoc/Classes/R ProgrammingForResearch_2022/Homework/HW5/homicide-data.csv")

# to make sure Denver is one of the cities
homicides %>% 
  select(city) %>% 
  distinct() %>% 
  pull()

#Making Denver dataset 
denver_homicides <- homicides %>% 
  filter(city == "Denver")

#group all unsolved homicides together in "unsolved" column
denver_homicides <- denver_homicides %>% 
  mutate(unsolved_homicides = disposition == "Closed without arrest" | 
           disposition == "Open/No arrest") 

# mutate TRUE and FALSE in "unsolved" column to "Solved" and "Unsolved"
denver_homicides <- denver_homicides %>% 
  mutate(unsolved_homicides = as_factor(x = unsolved_homicides),
         unsolved_homicides = fct_recode(unsolved_homicides, Solved = "TRUE", 
                                         Unsolved = "FALSE"))
# check towns
denver_homicides %>%
  mutate(victim_race = fct_lump(victim_race, n = 3)) %>%
  count(victim_race)
```

#sf map of denver, colorado
To download boundaries for some sub-city geography 
(e.g., tracts, block groups, county subdivisions) I used the sf package

```{r}
counties <- counties(state = "CO", cb = TRUE, class = "sf", 
                     progress_bar = FALSE)

blocks <- block_groups("CO", "Denver", progress_bar = FALSE)

ggplot() +
  geom_sf(data = blocks, fill = "antiquewhite", alpha = 0.5) +
  theme_bw()

```
#adding the homicides  
1- I used facet_wrap for solved versus unsolved homicides
2- I showed it as a layer underneath the points showing homicides.

```{r}
denver_homicides <- st_as_sf(denver_homicides, coords = c("lon", "lat")) %>% 
  st_set_crs(4269)

denver_homicides <- st_transform(denver_homicides, st_crs(blocks))

ggplot() +
  geom_sf(data = blocks, fill = "darkcyan", alpha = 0.5) +
  geom_sf(data = denver_homicides, aes(colour = city)) + 
  facet_wrap(~ unsolved_homicides) +
  theme_dark()
  
```


